apiVersion: v1
kind: Service
metadata:
  name: conversor-video-service
spec:
  selector:
    app: conversor-video
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007